// examples/next/app/page.tsx
export default function HomePage() {
  return (
    <main style={{ padding: '2rem', fontFamily: 'system-ui, sans-serif' }}>
      <h1>agent-devtools — Next.js example</h1>
      <p>
        This route is rendered by the App Router. The floating widget should appear in the
        bottom-right corner during <code>next dev</code>, and the production build should not ship
        any <code>@agent-devtools</code> code.
      </p>
      <p>
        See <a href="/hello">/hello</a> for the Pages Router smoke route.
      </p>
    </main>
  );
}

// examples/vue-vite/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import Counter from './components/Counter.vue';

const greeting = ref('agent-devtools Vue smoke');
</script>

<template>
  <main class="page">
    <h1>{{ greeting }}</h1>
    <p>
      Vite + Vue 3 host app that loads the floating widget through
      <code>@agent-devtools/vue</code>. Open the launcher in the bottom-right
      corner, pick the counter button, and the picker should resolve to the
      <code>Counter.vue</code> component.
    </p>
    <Counter />
  </main>
</template>

<style scoped>
.page {
  font-family: system-ui, -apple-system, 'Segoe UI', sans-serif;
  max-width: 36rem;
  margin: 3rem auto;
  padding: 0 1.25rem;
  line-height: 1.5;
}
h1 {
  margin-bottom: 0.5rem;
}
</style>
