// examples/sveltekit/src/lib/Counter.svelte
<script lang="ts">
  let count = $state(0);
</script>

<div class="counter">
  <button onclick={() => (count -= 1)} aria-label="decrement">−</button>
  <span class="value">{count}</span>
  <button onclick={() => (count += 1)} aria-label="increment">+</button>
</div>

<style>
  .counter {
    display: inline-flex;
    align-items: center;
    gap: 12px;
    padding: 12px 16px;
    border: 1px solid #e5e7eb;
    border-radius: 12px;
    background: #f9fafb;
  }
  .value {
    min-width: 24px;
    text-align: center;
    font-variant-numeric: tabular-nums;
    font-size: 18px;
    font-weight: 600;
  }
  button {
    width: 32px;
    height: 32px;
    border-radius: 8px;
    border: 1px solid #d1d5db;
    background: white;
    cursor: pointer;
    font-size: 16px;
  }
  button:hover {
    background: #f3f4f6;
  }
</style>

// examples/vue-vite/src/components/Counter.vue
<script setup lang="ts">
import { ref } from 'vue';

const count = ref(0);
</script>

<template>
  <section class="counter">
    <p>Count: {{ count }}</p>
    <button type="button" @click="count++">Increment</button>
  </section>
</template>

<style scoped>
.counter {
  display: flex;
  align-items: center;
  gap: 1rem;
}
button {
  padding: 0.4rem 0.9rem;
  border-radius: 6px;
  border: 1px solid #888;
  background: #fafafa;
  cursor: pointer;
}
</style>
