// examples/vue-vite/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import Counter from './components/Counter.vue';

const greeting = ref('agent-devtools Vue smoke');
</script>

<template>
  <main class="page">
    <h1>{{ greeting }}</h1>
    <p>
      Vite + Vue 3 host app that loads the floating widget through
      <code>@agent-devtools/vue</code>. Open the launcher in the bottom-right
      corner, pick the counter button, and the picker should resolve to the
      <code>Counter.vue</code> component.
    </p>
    <Counter />
  </main>
</template>

<style scoped>
.page {
  font-family: system-ui, -apple-system, 'Segoe UI', sans-serif;
  max-width: 36rem;
  margin: 3rem auto;
  padding: 0 1.25rem;
  line-height: 1.5;
}
h1 {
  margin-bottom: 0.5rem;
}
</style>

// examples/svelte-vite/src/App.svelte
<script lang="ts">
  import Counter from './lib/Counter.svelte';
</script>

<main>
  <header>
    <h1>agent-devtools · Svelte + Vite</h1>
    <p>Hover then click any element to pick it for the agent.</p>
  </header>
  <section>
    <Counter />
  </section>
</main>

<style>
  main {
    font-family: system-ui, sans-serif;
    max-width: 640px;
    margin: 48px auto;
    padding: 0 24px;
    color: #1f2937;
  }
  header h1 {
    margin: 0 0 8px;
    font-size: 24px;
  }
  header p {
    margin: 0 0 32px;
    color: #6b7280;
  }
</style>
